---
sudo: required

services:
  - docker

language: python
python: "2.7"

addons:
  apt:
    packages:
      - python-pip

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=alpine_3.5
  - OS=alpine_edge
  - OS=fedora_23
  - OS=fedora_24
  - OS=fedora_25
  - OS=debian_jessie
  - OS=ubuntu_xenial
    
before_install:
  - pip install ansible-galaxy-local-deps dcb==0.0.14
  - ansible-galaxy-local-deps-write

script:
  - >-
    dcb
    --snippetsdir .
    --snippet from.j2 ansible-playbook.j2
    --upstreamgroup andrewrothstein
    --upstreamapp docker-supervisord
    --pull ${OS}
    --write ${OS}
    --build ${OS}
    --push ${OS}
